# Generated by Django 3.1.7 on 2021-03-22 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210311_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время конца события'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала события'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smsauth',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
    ]
